# Generated by Django 4.1.7 on 2023-03-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'Female')], default='M', max_length=7),
        ),
    ]
